default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
<%
  if ENV['DOCKER_DATABASE_URL']
    database_name = URI(ENV['DOCKER_DATABASE_URL']).path[1..-1]
%>
  # url: <%= ENV['DOCKER_DATABASE_URL'] %> Needs Rails 4
  # postgresql://user:password@host:port/database


  username: <%= URI(ENV['DOCKER_DATABASE_URL']).user %>
  <% if URI(ENV['DOCKER_DATABASE_URL']).password.present? %>
  password: <%= URI(ENV['DOCKER_DATABASE_URL']).password %>
  <% end %>
  #host: <%= URI(ENV['DOCKER_DATABASE_URL']).host %>
  host: coderwall.local
  port: <%= URI(ENV['DOCKER_DATABASE_URL']).port %>
<%
  else
    database_name = 'coderwall'
%>

  username: vagrant
  password:
  host: localhost
  port: 5432
<% end %>

development:
  database: <%= "#{database_name}_development" %>
  <<: *default

test:
  database: <%= "#{database_name}_test" %>
  <<: *default

production:
  database: <%= "#{database_name}_production" %>
  <<: *default
