default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DEV_POSTGRES_HOST'] || 'localhost' %>
  password:
  pool: 5
  port: <%= ENV['DEV_POSTGRES_PORT'] || 5432 %>
  username: <%= ENV['DEV_POSTGRES_USER'] || 'vagrant' %>

development:
  <<: *default
  database: coderwall_development

test:
  <<: *default
  database: coderwall_test

production:
  <<: *default
  database: coderwall_production
