default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: vagrant
  host: localhost
  port: 5432
  password:

development:
  <<: *default
  database: coderwall_development

test:
  <<: *default
  database: coderwall_test

production:
  <<: *default
  database: coderwall_production
