development:
   sessions:
    default:
     database: badgify_development
     hosts:
      - localhost

test:
  sessions:
   default:
    database: badgify_test
    hosts:
     - localhost

staging:
  sessions:
   default:
    uri: <%= ENV['MONGOLAB_URI'] %>

production:
  sessions:
   default:
     uri: <%= ENV['MONGOLAB_URI'] %>
